src/data/members.json
hello there (I don't know why I always say that, haven't even seen the movie)
=> Added myself :P

src/data/members.json
```json
{
"title": "Alex (WingedDemonFox)",
"url": "https://wingeddemonfox.dev/",
"feed": "https://wingeddemonfox.dev/index.xml"
}
```
=> Adding wingeddemonfox

src/data/members.json
Example:
```json
{
"feed": null
}
```
=> Update members.json with herzamos.ch

src/data/members.json
People must really use these comments to document tons of things, considering the size of this comment box is huge.
Example:
```json
{
"feed": null
}
```
=> Added me (Azurios)

src/data/members.json
Example:
```json
{
"feed": null
}
```
=> added my blog 🥳

src/data/members.json
Check if everything's correct
Example:
```json
{
"feed": null
}
```
=> Added my blog

src/data/members.json
Adding my site even though it's basically empty right now
=> Added yet another blog

src/data/members.json
```json
{
"title": "Lukas Möller",
"url"  : "https://lukas-moeller.ch/blog",
"feed" : "https://lukas-moeller.ch/api/rss2.xml"
}
```
=> Add to member list

src/data/members.json
=> fixed feed url for ateon.ch

src/data/members.json
great polyring you built up here!
=> added my site :)

src/data/members.json
Thanks for all your work on this Julian!
=> Add "Luc Aggett" to the Ring

src/data/members.json
Currently there is no RSS feed, but as soon as I'll complete my blog, I will set one up and add it.
=> Added "danny@ETH" to the ring

src/data/members.json
Blog is now under a different URL
=> Update Luc Aggett (nothome.xyz) links

src/data/members.json
website is broken and I neither have time nor motivation to fix it or continue the blog
=> remove jonas

src/data/members.json
Thank you for this amazing idea!
=> Add "Kai Zheng" to the Ring

src/data/members.json
The given data is already in members.json but here
```json
}
"title": "Lu (chluebi)",
"url": "https://chluebi.com/",
"feed": "https://chluebi.com/index.xml"
}
```
=> added Lu (chluebi) to members

src/data/members.json
=> changed my RSS feed

src/data/members.json
```json
{
"title": "Thomas Gassmann",
"url": "https://thomasgassmann.com/",
"feed": "https://thomasgassmann.com/rss.xml"
}
```
=> Added myself

src/data/members.json
=> New Blog, Who Dis? :eyes: 

src/data/members.json
It was fun but I want to remove myself from here for now so I can rework and rethink the whole blog :3
=> Update members.json - removing myself

src/data/members.json
Example:
```json
{
"feed": null
}
```
=> add alxstai.com

src/data/members.json
Example:
```json
{
"feed": null
}
```
=> Add my site (:

src/data/members.json
Hi, I added myself to members.json 😄
=> Add myself

src/data/members.json
Hey Julian :smile: I've added my new blog to member.s.json
Many thanks and wishing you a happy new year!
=> chore: Added kalek.dev to members.json
